version: "3.9"
   
services:
  db:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: sgclinicaestetica_db
    volumes:
      - ./data/db/imperio:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    restart: always
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - db