FROM postgres

# Update package
RUN apt-get update
RUN export LC_ALL="pt_BR.UTF-8"
RUN export LC_CTYPE="pt_BR.UTF-8"

# Environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=imperio
